# Generated by Django 6.0.3 on 2026-04-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='duration',
            new_name='duration_seconds',
        ),
    ]
